services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: sh -c "npm run dev"
    volumes:
      - .:/src
      - node_modules:/src/node_modules
    ports:
      - 3000:3000
    environment:
      - NUXT_APP_BASE_URL=${BASE_URL}
      - NUXT_PUBLIC_ORIGIN=${ORIGIN}
      - NUXT_PUBLIC_BASE_URL=${BASE_URL}
    networks:
      - internal

  testapp:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        TESTING: 'true'
    command: sh -c "tail -f /dev/null"
    volumes:
      - .:/src
      - node_modules:/src/node_modules
    environment:
      - NUXT_APP_BASE_URL=${BASE_URL}
      - NUXT_PUBLIC_ORIGIN=${ORIGIN}
      - NUXT_PUBLIC_BASE_URL=${BASE_URL}
    networks:
      - test

volumes:
  node_modules:

networks:
  internal:
  test:
