name: Tests

on: [push]

jobs:
  code-quality-and-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: try to build the project
        run: npm i && npm run generate

      - name: run prettier checks
        run: npm run fmt:check

      - name: run linting
        run: npm run lint

      - name: run typescript checks
        run: npm run ts:check

      - name: run vitest:nuxt
        run: npm run test -- --run --project nuxt
